<<<<<<< HEAD
{
  "builds": [
    {
      "src": "index.html",
      "use": "@netlify/html"
    }
  ]
}
=======
{
  "builds": [
    {
      "src": "index.html",
      "use": "@netlify/html"
    }
  ]
}
>>>>>>> 77c99caeb74ed59a0756057e0d31bd7f715544f1
